import sys
import re

import pandas as pd

def clean_text(text):
    '''
    Function which uses regex on a piece of text to return only alphanumeric
    characters.

    Params
    ------
    text : str

    Returns
    -------
    cleaned_text : str
        
    '''
    cleaned_text = re.sub(r"http\S+", "", text) #remove urls
    cleaned_text=re.sub(r'\S+\.com\S+','',cleaned_text) #remove urls
    cleaned_text=re.sub(r'\@\w+','',cleaned_text) #remove mentions
    cleaned_text =re.sub(r'\#','',cleaned_text) #remove hashtags
    cleaned_text = re.findall(r'[A-Za-z]+',cleaned_text)
    cleaned_text = ' '.join(cleaned_text)

    return cleaned_text

def twint_mentions_to_df(twint_df):
    '''
    Function to search through twint tweet data for user mentions
    and return a dataframe containing a tweet id and mentioned username
    in each row.
    
    Params
    ------
    twint_df : Pandas DataFrame

    Returns
    -------
    tweet_mentions : Pandas DataFrame
        
    '''
    mentions = []
    temp_ids = twint_df['id'].values
    temp_mentions = twint_df['mentions'].values
    for i in range(len(temp_ids)):
        temp_list = list(temp_mentions[i].strip('][').replace("'","").split(', '))
        for mention in temp_list:
            if len(mention)>0:
                mentions.append([temp_ids[i], mention])
            
    tweet_mentions = pd.DataFrame(mentions, columns=['tweet_id', 'mentions'])
    return tweet_mentions

############################################################################################################################

def init_cleaned_tweet_df(): 
    '''
    Initialise and return an empty dataframe with a standard, curated set of fields.

    Returns
    -------
    standard_df : Pandas DataFrame
        A dataframe containing tweets with a standardised set of fields.
    '''
    standard_df = pd.DataFrame(
        columns = [ 'user_id', 'screen_name', 'name', # Fields that identify user
                    'tweet_id', 'text', 'tweet_created_at', # Basic tweet info
                    'conversation_id', 'in_reply_to_status_id', 'rt_id', # ID fields that help identify interactions
                    'rt_user_id', 'rt_screen_name', 'rt_text', # Retweet Fields
                    'in_reply_to_user_id', 'in_reply_to_screen_name', # Reply information
                    'quoted_status_id', 'quoted_status', # Quote tweet info
                    'replies_count', 'retweet_count', 'like_count', # Engagement stats
                    'hashtags'])
    return standard_df


############################################################################################################################

def clean_twint_dataframe(twint_df):
    '''
    A function to take tweet data generated by twint and return
    a standardised dataframe with a consistent set of fields.

    Params
    ------
    twint_df : Pandas DataFrame
        The twint tweet data to be processed and transferred.

    Returns
    -------
    standard_df : Pandas DataFrame
        A dataframe containing tweets with a standardised set of fields.
    '''
    standard_df = init_cleaned_tweet_df() # Initialise an empty dataframe
    # Start assigning the columns
    standard_df = pd.concat([standard_df, twint_df[twint_df.columns.intersection(standard_df.columns)]], axis=0)
    

    #tweet and conversation ID
    standard_df['tweet_id'] = twint_df['id']
    #conversation ID (twint) or in_reply_to_status_id (API)
    standard_df['conversation_id'] = twint_df['conversation_id']
    #reply to or reply to status_id
    standard_df['reply_to'] = twint_df['reply_to']
    #user id and it's screen_name
    standard_df['user_id'] = twint_df['user_id']
    standard_df['screen_name'] = twint_df['username']
    #date of tweet
    standard_df['tweet_created_at'] = twint_df['date'] + ' ' + twint_df['time']
    #Tweet text
    standard_df['text'] = twint_df['tweet']
    # Replies - RT - likes count
    standard_df['replies_count'] = twint_df['replies_count']
    standard_df['retweets_count'] = twint_df['retweets_count']
    standard_df['likes_count'] = twint_df['likes_count']
    #Hashtags
    standard_df['hashtags'] = twint_df['hashtags']
    
    
    # Check that the columns that contain strings have all lowercases
    standard_df['reply_to'] = standard_df['reply_to'].str.lower()
    standard_df['screen_name'] = standard_df['screen_name'].str.lower()
    standard_df['hashtags'] = standard_df['hashtags'].str.lower()
    
    return standard_df

############################################################################################################################

def clean_API_dataframe(API_df):
    '''
    A function to take tweet data generated by the twitter API and return
    a standardised dataframe with a consistent set of fields.

    Params
    ------
    API_df : Pandas DataFrame
        The API tweet data to be processed and transferred.

    Returns
    -------
    standard_df : Pandas DataFrame
        A dataframe containing tweets with a standardised set of fields.
    '''
    # Initialise standardised dataframe
    standard_df = init_cleaned_tweet_df()
    # Automatically fill columns that have matching names already
    standard_df = pd.concat([standard_df, API_df[API_df.columns.intersection(standard_df.columns)]], axis=0)
    # Fill other desired columns where names dont match
    standard_df['like_count'] = API_df['favorite_count']

    # Set certain string columns to lowercase
    lowercase_list = ['in_reply_to_screen_name', 'screen_name', 'rt_screen_name', 'hashtags']
    for item in lowercase_list:
        standard_df[item] = standard_df[item].str.lower()

    to_clean_list = ['text', 'rt_text']
    for item in to_clean_list:
        standard_df[item] = standard_df[item].apply(lambda text : clean_text(text) if isinstance(text, str) else 'None')
    
    return standard_df

def populate_user_df(user_data):
    '''
    Take a series of tweepy user objects and transform them into a dataframe.
    
    Params
    ------
    user_data : list
        List of tweepy.User objects 
    
    Returns
    -------
    user_df : Pandas DataFrame
        Cleaned dataframe with user data.
    '''
    df_fields = ['user_id', 'screen_name',  'name', 'location', 'user_description', 
              'user_friends_n', 'user_followers_n', 'prof_created_at', 'favourites_count', 
              'verified', 'statuses_count']
    
    API_fields = ['id', 'screen_name', 'name', 'location', 'description', 
                  'friends_count', 'followers_count', 'created_at', 'favourites_count',
                 'verified', 'statuses_count']
    # Go through tweepy user objects and pull relevant data into lists
    full_list = []
    for user in user_data:
        user_vars = vars(user)
        data_list = [user_vars[field] for field in API_fields]
        full_list.append(data_list)
    # Translate data list into dataframe
    user_df = pd.DataFrame(full_list, columns=df_fields)
    # Additional cleaning of data in dataframe
    user_df['screen_name'] = user_df['screen_name'].str.lower()
    standard_df['user_description'] = standard_df['user_description'].apply(lambda text : clean_text(text) if isinstance(text, str) else 'None')
    
    return user_df